---
kind: pipeline
name: test-on-amd64

platform:
  arch: amd64

steps:
- name: test
  image: gcc
  commands:
  - ./configure
  - make
  - make test

---
kind: pipeline
name: test-on-arm64

platform:
  arch: arm64

steps:
- name: test
  image: gcc
  commands:
  - ./configure
  - make
  - make test

...
